# Use the official MariaDB image from Docker Hub
FROM mariadb:latest
# Copy custom configuration file if needed
# COPY ./custom.cnf /etc/mysql/conf.d/custom.cnf

# Expose port 3306 to allow outside access to the database
EXPOSE 3306
